services:
  web:
    build: .
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb
    ports:
      - 80:3000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
